name: Self-hosted runner (nightly-past-ci-caller)

on:
  schedule:
    # 2:17 am on each Sunday and Thursday

    - cron: "17 2 * * 0,4"
  push:
    branches:
      - run_nightly_ci*
      - run_past_ci*
      - run_use_nightly_accelerate_in_past_ci

jobs:
  run_past_ci_pytorch_1-13:
    name: PyTorch 1.13
    if: (cancelled() != true) && ((github.event_name == 'schedule') || ((github.event_name == 'push') && startsWith(github.ref_name, 'run_use_nightly_accelerate_in_past_ci')))
    uses: ./.github/workflows/self-past.yml
    with:
      framework: pytorch
      version: "1.13"
      sha: ${{ github.sha }}
    secrets: inherit
